Sur une amélioration, je peux ajouter une photo
re-connect/mpb pull request #103
Opened 2023-04-19 09:48 UTC by AntoineAresu

[Ticket](https://trello.com/c/dMWaYJRn/3546-35-sur-une-am%C3%A9lioration-je-peux-ajouter-une-photo-same-as-sur-les-bugs)

2023-04-19 10:49 UTC, tcheymol requested changes

2023-04-19 10:49 UTC, tcheymol commented on src/Entity/Feature.php
> +    #[ORM\Column(type: 'string', nullable: true, enumType: FeatureStatus::class, options: ['default' => 'TO_BE_DECIDED'])]
Il faut pas une constante ?

2023-04-19 10:49 UTC, tcheymol commented on src/Service/AttachmentService.php
> +        $name = Uuid::v4().'.'.$file->guessExtension();
Could it be some exceptions around here, and edge cases regarding the guessExtension method

2023-04-19 10:49 UTC, tcheymol commented on src/Traits/UploadableTrait.php
> +    public function addAttachment(Attachment $attachment): static
you mix static and self returns here and in the Draftable Trait

2023-04-19 10:49 UTC, tcheymol commented on templates/bug/_attachment_widget.html.twig
> +{{ include('attachment/_widget.html.twig', {
is this template useful ?

2023-04-19 10:49 UTC, tcheymol commented on templates/feature/components/_attachment_widget.html.twig
> +{{ include('attachment/_widget.html.twig', {
same

2023-04-20 06:59 UTC, NilsRec commented on src/Entity/Attachment.php
> +    #[ORM\ManyToOne(targetEntity: Feature::class, inversedBy: 'attachments')]
On pourrait ajouter une contrainte de type expression, qui vérifie qu'au moins un des deux n'est pas null entre bug et feature

2023-04-20 07:05 UTC, NilsRec commented on src/Controller/FeatureController.php
> +    public function edit(Request $request, Feature $feature, FeatureManager $manager): Response
J'ai l'impression qu'il y a une route en trop entre new et edit, ça ne pourrait pas être la même ?

2023-04-20 07:07 UTC, NilsRec commented on templates/feature/components/_card.html.twig
> +            {% endif %}
Ternaire  plutôt ?

2023-04-20 07:09 UTC, NilsRec commented on templates/feature/edit.html.twig
> +    {{ include('feature/components/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
Traduction du button_label. 
Ceci dit vu mon commentaire plus haut sur la nécessité d'avoir deux routes (new et edit), peut-être qu'on peut se passer de ce template

2023-04-21 05:51 UTC, AntoineAresu commented on src/Controller/FeatureController.php
> +    public function edit(Request $request, Feature $feature, FeatureManager $manager): Response
La route edit nécessite la permission d'update une feature contrairement à la route create

2023-05-02 09:05 UTC, tcheymol requested changes

2023-05-02 09:05 UTC, tcheymol commented on src/Service/AttachmentService.php
> +    public function addAttachment(UserRequest $userRequest, mixed $file): bool
You should at least phpdoc the $file mixed type

2023-05-02 09:05 UTC, tcheymol commented on src/Service/AttachmentService.php
> +        }
I think one condition would be enough

2023-05-02 09:05 UTC, tcheymol commented on src/Traits/DraftableTrait.php
> +    public function setDraft(bool $draft): static
return  type self I guess

2023-05-02 09:05 UTC, tcheymol commented on src/Traits/DraftableTrait.php
> +    public function publish(): static
same

2023-05-02 09:05 UTC, tcheymol commented on src/Traits/UploadableTrait.php
> +    public function getAttachments(): Collection
I think this should be ReadableCollection

2023-05-02 09:05 UTC, tcheymol commented on templates/feature/edit.html.twig
> +    <h1>{{ 'update_feature'|trans }}</h1>
We could maybee have this h1 directly using the content of title in the parent  template

2023-05-02 13:11 UTC, AntoineAresu commented on src/Traits/DraftableTrait.php
> +    public function setDraft(bool $draft): static
static va permettre de retourner un objet de type UserRequest ou sa classe enfant, ce qui peut être utile

2023-05-02 13:21 UTC, merged